### ISSUE TITLE
[Issue] donutCS does not close file handle for InputFile

### ISSUE THREAD

**Issue by cobbr** [n1xbyte/donutCS#3]
Hey @n1xbyte , I believe we have identified a bug in donutCS where the InputFile inside a `DonutConfig` is not released after a call to `Generator.Donut_Create()`

This means that we cannot pass in the same InputFile to multiple `Generator.Donut_Create()` calls without killing the calling process first.

I'm not sure yet whether this is an issue with donutCS itself or with the PeNet dependency, but my bet is that it's the PeNet dependency. It looks like PeNet has updated many times since the last donutCS was released, maybe a simple dependency update would fix the problem?

Here's the related Covenant issue: https://github.com/cobbr/Covenant/issues/292

**Comment by cobbr** [comment]
Have any luck with this @n1xbyte ?

**Comment by b4rtik** [comment]
Hi,
I am having the same problem in another project. I believe the problem is related to how to read the source file to copy the PIC module data to instance.
I solved it by first reading the entire file and then creating an unmanaged pointer to the resulting byte array

```
            // if PIC, copy payload to instance
            if (inst.type == Constants.DONUT_INSTANCE_PIC)
            {
                D.Print($"Copying PIC module data to instance");
                // Copy payload file to end of module
                /*var mmfile = MemoryMappedFile.CreateFromFile(Helper.String(config.file), FileMode.Open);
                var view = mmfile.CreateViewAccessor();
                byte* fileptr = (byte*)0;
                view.SafeMemoryMappedViewHandle.AcquirePointer(ref fileptr);*/
                
                byte[] b = File.ReadAllBytes(Helper.String(config.file));
                IntPtr unmanagedPointer = Marshal.AllocHGlobal(b.Length);
                Marshal.Copy(b, 0, unmanagedPointer, b.Length);

                Buffer.MemoryCopy(unmanagedPointer.ToPointer(), IntPtr.Add(moddata, fileoffset).ToPointer(), config.mod.len, config.mod.len);
                // mmfile.Dispose();
                Marshal.FreeHGlobal(unmanagedPointer);
            }
```

Hope it helps

**Comment by n1xbyte** [comment]
Tested and fixed issue with the code above. Thanks @b4rtik!
